name: nemo_eyetracking
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - bottleneck
  - brotli
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cycler
  - et_xmlfile
  - expat
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - gettext
  - giflib
  - gmp
  - graphite2
  - harfbuzz
  - hdf5
  - icu
  - intel-openmp
  - ipykernel
  - jasper
  - jbig
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - liblapack
  - liblapacke
  - libnghttp2
  - libopencv
  - libpng
  - libprotobuf
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libzlib
  - llvm-openmp
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - numexpr
  - numpy
  - numpy-base
  - olefile
  - opencv
  - openh264
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pcre
  - pillow
  - pip
  - pixman
  - py-opencv
  - pyparsing
  - python=3.9.12
  - python-dateutil
  - python_abi
  - pytz
  - scikit-learn=1.0.2
  - scipy
  - seaborn
  - setuptools
  - six
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - tzdata
  - wheel
  - x264
  - xz
  - zlib
  - zstd
  - shapely # for handling polygons
  - svg.path # for parsing svg-paths
  - lifelines # for cox regression
  - pip:
    - i2mc==2.1.1
prefix: /Users/4137477/opt/anaconda3/envs/nemo_eyetracking
